# Schema for the configuration files of the SimpleSAMLphp_auth module.

simplesamlphp_auth.settings:
  type: mapping
  label: 'SimpleSAMLphp Auth Settings'
  mapping:
    activate:
      type: boolean
      label: 'Activate authentication via SimpleSAMLphp'
    auth_source:
      type: string
      label: 'Authentication source for this SP'
    force_https:
      type: boolean
      label: 'Force https for login links'
    user_name:
      type: string
      label: 'SimpleSAMLphp attribute to be used as username for the user'
    unique_id:
      type: string
      label: 'SimpleSAMLphp attribute to be used as unique identifier for the user'
    mail_attr:
      type: string
      label: 'SimpleSAMLphp attribute to be used as email address for the user'
    role:
      type: mapping
      label: 'Role population'
      mapping:
        population:
          type: string
          label: 'Automatic role population from simpleSAMLphp attributes'
        eval_every_time:
          type: boolean
          label: 'Reevaluate roles every time the user logs in'
    register_users:
      type: boolean
      label: 'Register users'
    allow:
      type: mapping
      label: 'Drupal authentication'
      mapping:
        set_drupal_pwd:
          type: boolean
          label: 'Allow SAML users to set Drupal passwords'
        default_login:
          type: boolean
          label: 'Allow authentication with local Drupal accounts'
        # @TODO string isn't the correct type here.
        default_login_roles:
          type: string
          label: 'Roles to be allowed to log in locally'
        default_login_users:
          type: string
          label: 'Users to be allowed to log in locally'
    logout_goto_url:
      type: string
      label: 'Redirect users after logging out'
    user_register_original:
      type: string
      label: 'Original user register status'
